compute_environment: LOCAL_MACHINE
deepspeed_config:
 deepspeed_config_file: /locate_to_config_file/zero_stage2_config.json
 zero3_init_flag: true
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: xx.xxx.72.6
main_process_port: 29346
main_training_function: main
#mixed_precision: fp16
num_machines: 2
num_processes: 8
use_cpu: false
