#集群名称
cluster.name: "es_cluster"
network.host: 0.0.0.0
discovery.seed_hosts: ["0.0.0.0"]
#跨域设置
http.cors.enabled: true
http.cors.allow-origin: "*"
#http端口
http.port: 9200
#java端口
transport.tcp.port: 9300
#xpack
xpack.security.enabled: false #最关键的一句
xpack.security.transport.ssl.enabled: false
